/**
 * Stamps build metadata (git commit, timestamp) into src/build-info.ts
 * Run before `ng build`: node stamp-build.js
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const commitHash = execSync('git rev-parse --short HEAD').toString().trim();
const commitMsg = execSync('git log -1 --pretty=%s').toString().trim();
const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
const buildTime = new Date().toISOString();

const content = `// Auto-generated by stamp-build.js — do not edit
export const BUILD_INFO = {
  commit: '${commitHash}',
  message: '${commitMsg.replace(/'/g, "\\'")}',
  branch: '${branch}',
  buildTime: '${buildTime}',
};
`;

const outPath = path.join(__dirname, 'src', 'build-info.ts');
fs.writeFileSync(outPath, content, 'utf-8');
console.log(`Build info stamped: ${commitHash} (${branch}) at ${buildTime}`);
