import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Baseline schema — creates the full core schema that `synchronize` used to build
 * implicitly on boot. With this in place, `migrationsRun` can build a fresh DB
 * from nothing, so `DB_SYNCHRONIZE=false` is safe. Ordered FIRST (timestamp before
 * TenantFoundation); the existing incremental migrations then run idempotently on
 * top (every CREATE TABLE / ADD COLUMN they do is guarded with IF [NOT] EXISTS).
 *
 * SELF-GUARDING: if a core table already exists, the DB was built by `synchronize`
 * (the established dev/prod DBs), so the whole baseline no-ops — flipping
 * DB_SYNCHRONIZE=false on an existing DB is therefore safe with no manual
 * migrations-table seeding. On a truly empty DB it builds everything.
 */
export class BaselineSchema1780700000000 implements MigrationInterface {
    name = 'BaselineSchema1780700000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Already built by synchronize? Then this baseline is a no-op.
        if (await queryRunner.hasTable('organizations')) return;
        // The uuid PK defaults below need uuid-ossp; later migrations also use
        // gen_random_uuid() (pgcrypto). synchronize relied on these being present.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);

        await queryRunner.query(`CREATE TABLE "stages" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "process_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "sequence" integer NOT NULL, "target_time_seconds" integer NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "requires_inspection" boolean NOT NULL DEFAULT false, "inspection_type" character varying(16), "is_final_qc" boolean, "inspection_characteristics" jsonb, "required_signoff_role" character varying(60), "hourly_rate" numeric(10,2), "machine_time_seconds" integer NOT NULL DEFAULT '0', "machine_rate" numeric(12,2), "overhead_percent" numeric(6,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b48b7fae326a54c05490f46721e" UNIQUE ("process_id", "sequence"), CONSTRAINT "PK_16efa0f8f5386328944769b9e6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_788b52632a8883adcab17800b9" ON "stages" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "processes" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "version" integer NOT NULL DEFAULT '1', "library_origin_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_566885de50f7d20a6df306c12e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76392b0d423d52a89de847905c" ON "processes" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c520fd9491180bab8038d68ed9" ON "processes" ("library_origin_id") `);
        await queryRunner.query(`CREATE TYPE "public"."stations_type_enum" AS ENUM('laser', 'saw', 'drill', 'fit_up', 'weld', 'blast', 'paint', 'qc', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."stations_status_enum" AS ENUM('available', 'running', 'idle', 'setup', 'down', 'maintenance', 'offline')`);
        await queryRunner.query(`CREATE TABLE "stations" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(100), "description" text, "type" "public"."stations_type_enum" NOT NULL DEFAULT 'other', "status" "public"."stations_status_enum" NOT NULL DEFAULT 'available', "line_id" uuid NOT NULL, "machine_rate" numeric(12,2), "available_hours_per_day" numeric(6,2), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4eeb7798ea871c034351fa945ee" UNIQUE ("name", "line_id"), CONSTRAINT "PK_f047974bd453c85b08bab349367" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fecc585b9225ade4dc2b28e47" ON "stations" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "lines" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_155ad34738bc0e1aab0ca198dea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fcadab7665a53629719a6c7de" ON "lines" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_lines_org_name" ON "lines" ("organization_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."import_files_status_enum" AS ENUM('uploaded', 'converting', 'extracting', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "import_files" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "original_name" character varying(255) NOT NULL, "format" character varying(20) NOT NULL, "storage_key" character varying(500), "size" integer, "status" "public"."import_files_status_enum" NOT NULL DEFAULT 'uploaded', "stage" character varying(30) NOT NULL DEFAULT 'uploaded', "progress" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "duration_ms" integer, "created_by_id" uuid, "created_by_name" character varying(200), "revision" jsonb, "conversion_job_id" uuid, "model_id" uuid, "node_count" integer NOT NULL DEFAULT '0', "error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_45cc3f75a8fcd2972c1201a4911" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b4bbc007af39ae1898af1e6b9" ON "import_files" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_35f1f7d05b762cd089a73eaff8" ON "import_files" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "projects" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "project_number" character varying(100), "client_name" character varying(255), "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_585c8ce06628c70b70100bfb84" ON "projects" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2660bc3e8efca00003ad93568f" ON "projects" ("organization_id", "project_number") `);
        await queryRunner.query(`CREATE TABLE "models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "file_name" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "file_path" character varying(500) NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying(100) NOT NULL, "file_format" character varying(20) NOT NULL DEFAULT 'glb', "model_type" character varying(50) NOT NULL DEFAULT 'assembly', "thumbnail_path" character varying(500), "assembly_instructions" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef9ed7160ea69013636466bf2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assembly_nodes_node_type_enum" AS ENUM('group', 'assembly', 'subassembly', 'part')`);
        await queryRunner.query(`CREATE TABLE "assembly_nodes" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "parent_id" uuid, "node_type" "public"."assembly_nodes_node_type_enum" NOT NULL DEFAULT 'part', "name" character varying(255) NOT NULL, "mark" character varying(100), "quantity" integer NOT NULL DEFAULT '1', "ifc_guid" character varying(64), "ifc_class" character varying(64), "source_format" character varying(20), "import_file_id" uuid, "profile" character varying(120), "material_grade" character varying(60), "length_mm" numeric(12,2), "weight_kg" numeric(12,3), "properties" jsonb, "model_id" uuid, "mesh_name" character varying(255), "depth" integer NOT NULL DEFAULT '0', "sort_index" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e214aa879f114253d5a6231bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f7afa487ac07d715765f29dcf" ON "assembly_nodes" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_66019f5d0f82c8f82e0086a8bf" ON "assembly_nodes" ("organization_id", "project_id", "ifc_guid") `);
        await queryRunner.query(`CREATE INDEX "IDX_487a5538402a7d98120d2f67ac" ON "assembly_nodes" ("organization_id", "project_id", "mark") `);
        await queryRunner.query(`CREATE INDEX "IDX_381643ecf1cbccbdd4cf2202ab" ON "assembly_nodes" ("organization_id", "parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f18710a23bb84e19152c03702" ON "assembly_nodes" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."work_orders_status_enum" AS ENUM('draft', 'pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."work_orders_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "work_orders" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying(50) NOT NULL, "process_id" uuid NOT NULL, "line_id" uuid, "assembly_node_id" uuid, "production_order_id" uuid, "quantity" integer NOT NULL, "completed_quantity" integer NOT NULL DEFAULT '0', "status" "public"."work_orders_status_enum" NOT NULL DEFAULT 'draft', "priority" "public"."work_orders_priority_enum" NOT NULL DEFAULT 'medium', "due_date" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "depends_on_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5de6484bf0a3780b60adbad0965" UNIQUE ("order_number"), CONSTRAINT "PK_29f6c1884082ee6f535aed93660" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce134ea8fbde02d6ea7ef47689" ON "work_orders" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "role_permission_grants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "permission" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f2a613c62bb031bbce5a859116" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e9395b394d1491a03a9085ae7" ON "role_permission_grants" ("role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_role_permission_grant" ON "role_permission_grants" ("role_id", "permission") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" text, "organization_id" uuid, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c328a1ecd12a5f153a96df4509" ON "roles" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_org_name" ON "roles" ("organization_id", "name") WHERE "organization_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_system_name" ON "roles" ("name") WHERE "organization_id" IS NULL`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" character varying(50) NOT NULL, "email" character varying(255), "mobile_no" character varying(15), "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "role_id" uuid NOT NULL, "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "tour_state" jsonb, "hourly_rate" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9760615d88ed518196bb79ea03d" UNIQUE ("employee_id"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21a659804ed7bf61eb91688dea" ON "users" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."work_order_stages_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "work_order_stages" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "work_order_id" uuid NOT NULL, "stage_id" uuid NOT NULL, "assigned_user_id" uuid, "station_id" uuid, "status" "public"."work_order_stages_status_enum" NOT NULL DEFAULT 'pending', "qty_total" integer, "qty_done" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "actual_time_seconds" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e50f095f191afc8033afdf0702" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2abb3c5f7c23f6ea78cc9f0391" ON "work_order_stages" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "work_order_stage_events" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "work_order_stage_id" uuid NOT NULL, "work_order_id" uuid NOT NULL, "production_order_id" uuid, "assembly_node_id" uuid, "stage_name" character varying(120), "user_id" uuid, "action" character varying(20) NOT NULL, "from_status" character varying(20), "to_status" character varying(20), "from_qty" integer, "to_qty" integer, "source" character varying(10) NOT NULL DEFAULT 'web', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_860638551178164d2b93511658e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70a8a30750743c1f083ab452b3" ON "work_order_stage_events" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b253ddb0efc29fd573fd353e88" ON "work_order_stage_events" ("assembly_node_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_53da8dfea1358f1dd838ed483d" ON "work_order_stage_events" ("production_order_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_input_method_enum" AS ENUM('web', 'mobile', 'badge', 'kiosk')`);
        await queryRunner.query(`CREATE TABLE "time_entries" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "work_order_stage_id" uuid NOT NULL, "station_id" uuid, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP, "duration_seconds" integer, "break_seconds" integer NOT NULL DEFAULT '0', "idle_seconds" integer NOT NULL DEFAULT '0', "input_method" "public"."time_entries_input_method_enum" NOT NULL DEFAULT 'web', "is_rework" boolean NOT NULL DEFAULT false, "is_setup" boolean NOT NULL DEFAULT false, "labor_rate" numeric(10,2), "machine_rate" numeric(12,2), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1ad7e6b1c1fb01c90b557effb" ON "time_entries" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."production_orders_status_enum" AS ENUM('planned', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "production_orders" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "number" character varying(50) NOT NULL, "customer_name" character varying(255), "quantity" integer NOT NULL DEFAULT '1', "process_id" uuid, "status" "public"."production_orders_status_enum" NOT NULL DEFAULT 'planned', "due_date" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_95941cd3171ce211861f673f80d" UNIQUE ("number"), CONSTRAINT "PK_44d72e026027e3448b5d655e16e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d48deb499cd3c305e5ee88794f" ON "production_orders" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc9d16f42c918512af1d0ac33b" ON "production_orders" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "shipment_items" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "assembly_node_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7dfc873be1417190f0e5e001dd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40f37aa9652926851c630281e5" ON "shipment_items" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_793441b3ca5b4e860cbbc0ba63" ON "shipment_items" ("organization_id", "shipment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('planned', 'loaded', 'shipped', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "production_order_id" uuid, "project_id" uuid NOT NULL, "shipment_number" character varying(50) NOT NULL, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'planned', "destination" character varying(255), "carrier" character varying(255), "planned_date" TIMESTAMP, "shipped_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a2ee35581721926841ca73b31" ON "shipments" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_91cdde92701b89379e45888412" ON "shipments" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a00e535c74076ab850ff565b0" ON "shipments" ("organization_id", "production_order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."quality_reports_status_enum" AS ENUM('draft', 'submitted')`);
        await queryRunner.query(`CREATE TABLE "quality_reports" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying(50) NOT NULL, "template_id" uuid, "template_name" character varying(255) NOT NULL, "template_type" character varying(40), "template_schema" jsonb NOT NULL, "production_order_id" uuid NOT NULL, "project_id" uuid, "assembly_node_id" uuid, "stage_id" uuid, "work_order_stage_id" uuid, "source_quality_data_id" uuid, "data" jsonb, "status" "public"."quality_reports_status_enum" NOT NULL DEFAULT 'draft', "filled_by" uuid, "submitted_at" TIMESTAMP, "ncr_status" character varying(24), "disposition" character varying(24), "disposition_notes" text, "disposition_by" uuid, "disposition_at" TIMESTAMP, "root_cause" text, "corrective_action" text, "concession_by" uuid, "concession_reason" text, "resolved_at" TIMESTAMP, "resolved_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8b80e2ac9fe6850519b5616738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_361c1a31a625fb13f609b06897" ON "quality_reports" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4a2789da6c45f6d263954b0964" ON "quality_reports" ("organization_id", "number") `);
        await queryRunner.query(`CREATE INDEX "IDX_76f8c9297ae2598ae43b169a14" ON "quality_reports" ("organization_id", "assembly_node_id", "stage_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7a30142ee6935923ecfa7215c" ON "quality_reports" ("organization_id", "assembly_node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76f65e714e475e6c0463db1b45" ON "quality_reports" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5357c80fe58ddf03ba26244de" ON "quality_reports" ("organization_id", "production_order_id") `);
        await queryRunner.query(`CREATE TABLE "quality_report_events" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "type" character varying(24) NOT NULL, "from_status" character varying(24), "to_status" character varying(24), "disposition" character varying(24), "note" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f0209ad88be67f4a57d4e163030" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71e829797490fa916e92a5603f" ON "quality_report_events" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_970334f619ba2b1ce2a2dfbb29" ON "quality_report_events" ("organization_id", "report_id") `);
        await queryRunner.query(`CREATE TABLE "quality_data" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_key" uuid, "model_id" uuid NOT NULL, "mesh_name" character varying(255) NOT NULL, "region_label" character varying(255), "status" character varying(20) NOT NULL, "inspector" character varying(100), "inspector_user_id" uuid, "inspection_date" TIMESTAMP, "notes" text, "defect_type" character varying(100), "severity" character varying(20), "measurement_value" numeric(10,4), "measurement_unit" character varying(50), "tolerance_min" numeric(10,4), "tolerance_max" numeric(10,4), "assembly_node_id" uuid, "project_id" uuid, "stage_id" uuid, "work_order_stage_id" uuid, "signoff_status" character varying(20) NOT NULL DEFAULT 'pending', "signoff_by" character varying(100), "signoff_by_user_id" uuid, "signoff_date" TIMESTAMP, "signoff_notes" text, "attachments" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e25217fe65053b62ea5de2a4913" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4710e9b0f5968609f1109d42b0" ON "quality_data" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_quality_data_org_client_key" ON "quality_data" ("organization_id", "client_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_cab557211fa4769d2c1de5df37" ON "quality_data" ("organization_id", "signoff_status", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c91381ec2180cee025ad8e243a" ON "quality_data" ("organization_id", "assembly_node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bea2a0f82f98179feec4a26961" ON "quality_data" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2bfde750b655d3650bf644a73" ON "quality_data" ("organization_id", "model_id") `);
        await queryRunner.query(`CREATE TABLE "material_lots" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "material_id" uuid NOT NULL, "lot_number" character varying(100) NOT NULL, "heat_number" character varying(100), "supplier" character varying(255), "cert_reference" character varying(255), "received_quantity" numeric(14,3) NOT NULL DEFAULT '0', "remaining_quantity" numeric(14,3) NOT NULL DEFAULT '0', "received_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_246e7cb1b548ba58d4011f56006" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_668889d42df3e9a9af7577f331" ON "material_lots" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1375b8eb706d8125fd8fe78fc9" ON "material_lots" ("organization_id", "lot_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_55ba706b1d82e2d6fb7df3ce4d" ON "material_lots" ("organization_id", "material_id") `);
        await queryRunner.query(`CREATE TABLE "piece_lot_assignments" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "node_id" uuid NOT NULL, "material_lot_id" uuid NOT NULL, "quantity" numeric(14,3) NOT NULL DEFAULT '1', "note" character varying(300), "created_by_id" uuid, "created_by_name" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3ee1f33eb7cf69e6fb0c1083ccd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d48c311c2c30f55009bff846bf" ON "piece_lot_assignments" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f553480ff8c5f7e0f1b331ea1" ON "piece_lot_assignments" ("material_lot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5ec726f130adf0603bf999d90" ON "piece_lot_assignments" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ce72a36dc648bf61e13b10ab6" ON "piece_lot_assignments" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "assembly_documents" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "node_id" uuid, "import_file_id" uuid, "original_name" character varying(255) NOT NULL, "content_type" character varying(100) NOT NULL, "size" integer NOT NULL, "storage_key" character varying(500) NOT NULL, "label" character varying(200), "created_by_id" uuid, "created_by_name" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1fe7218c5b51458066849e9e7bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99d3e233142b752977c13bfab9" ON "assembly_documents" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ef39c4083166064de6685d38c" ON "assembly_documents" ("import_file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_901daaec4dbceb0444c7551894" ON "assembly_documents" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ada568171c79bbb5571b2a2a59" ON "assembly_documents" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "import_file_events" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_file_id" uuid NOT NULL, "project_id" uuid NOT NULL, "stage" character varying(30) NOT NULL, "status" character varying(20) NOT NULL, "progress" integer NOT NULL DEFAULT '0', "message" character varying(500) NOT NULL, "detail" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9fcfbc19c1ffb46c828e49b75f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f2bede4beb15c252a3dcacac6" ON "import_file_events" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_627c8bd2a3aa9d45af9b3b0858" ON "import_file_events" ("import_file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_491e12de5d7a90a5423fc8072c" ON "import_file_events" ("organization_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(100) NOT NULL, "kind" character varying(20) NOT NULL DEFAULT 'tenant', "description" text, "is_active" boolean NOT NULL DEFAULT true, "settings" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_963693341bd612aa01ddf3a4b68" UNIQUE ("slug"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('work_order_assigned', 'work_order_status', 'work_order_overdue', 'quality_fail', 'quality_signoff', 'efficiency_drop', 'station_idle', 'shift_summary', 'ncr_overdue', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'system', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "is_read" boolean NOT NULL DEFAULT false, "entity_type" character varying(50), "entity_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drawings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "drawing_number" character varying(100), "revision" character varying(50), "drawing_type" character varying(50) NOT NULL DEFAULT 'detail', "file_name" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "file_path" character varying(500) NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying(100) NOT NULL DEFAULT 'application/pdf', "model_id" uuid, "package_name" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bb1d1d1ceb57a1868e1d39e02bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coordination_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "project_name" character varying(255), "model_id" uuid, "kss_file_name" character varying(255), "kss_data" jsonb, "source_file" character varying(500), "detail_drawing_count" integer NOT NULL DEFAULT '0', "erection_drawing_count" integer NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'processing', "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2dc73b9edf4abd60be80f15019" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversion_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "original_name" character varying(255) NOT NULL, "source_format" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "progress" integer NOT NULL DEFAULT '0', "source_key" character varying(500), "source_size" integer, "source_hash" character varying(80), "output_key" character varying(500), "output_size" integer, "triangles_before" integer, "triangles_after" integer, "model_id" uuid, "name" character varying(255), "description" text, "model_type" character varying(50) NOT NULL DEFAULT 'assembly', "options" jsonb, "dimensions" jsonb, "error" text, "duration_ms" integer, "created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9828428ad66accbdc91e614befe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a31251121c74bea553cffa061" ON "conversion_jobs" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_61b3cb192f70b46dcaf7ca293f" ON "conversion_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c519fa5a72f430878c903cde75" ON "conversion_jobs" ("source_hash") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action" character varying(50) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "old_values" jsonb, "new_values" jsonb, "ip_address" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skills" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d51714a98b706cc16e11f8f3f" ON "skills" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_617f093918468c351bf240eea4" ON "skills" ("organization_id", "code") `);
        await queryRunner.query(`CREATE TABLE "shifts" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "start_time" character varying(5) NOT NULL, "end_time" character varying(5) NOT NULL, "days_of_week" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ff650d103d30e94e1e9ea2163" ON "shifts" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "shift_assignments" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "shift_id" uuid NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a78d24f38deedd9fe0ea19685c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a4882243be4521b3aad46e74e" ON "shift_assignments" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_39939165471c9a9d17325edc87" ON "shift_assignments" ("organization_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "employee_skills" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "skill_id" uuid NOT NULL, "level" character varying(50), "certified_at" TIMESTAMP, "expires_at" TIMESTAMP, "certified_by" uuid, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e74b1e2cad6e8aba5368ff116a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54858677e7532654a5fc12b994" ON "employee_skills" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ec563056f0d5955ed01edc340" ON "employee_skills" ("organization_id", "user_id", "skill_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('present', 'absent', 'leave', 'holiday')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL, "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'present', "clock_in_at" TIMESTAMP, "clock_out_at" TIMESTAMP, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14db12e7c45733ec3a07d1160c" ON "attendance" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e04118de3e868864d6a56a0cda" ON "attendance" ("organization_id", "user_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."serial_units_status_enum" AS ENUM('in_production', 'completed', 'shipped', 'scrapped')`);
        await queryRunner.query(`CREATE TABLE "serial_units" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serial_number" character varying(120) NOT NULL, "work_order_id" uuid, "status" "public"."serial_units_status_enum" NOT NULL DEFAULT 'in_production', "produced_at" TIMESTAMP, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5de6e659b8a94f0b8735de582bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b72b223a1faab13611a89c3bad" ON "serial_units" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_79657a3cb8c19f6301ea7d6b73" ON "serial_units" ("organization_id", "work_order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4d8cd27d8289ad569661e0786e" ON "serial_units" ("organization_id", "serial_number") `);
        await queryRunner.query(`CREATE TABLE "genealogy_links" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serial_id" uuid NOT NULL, "material_lot_id" uuid NOT NULL, "quantity" numeric(14,3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5cdad9dc9fe953dceb7b973b4b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6aea3bacc6a4c6a40cbf63a35" ON "genealogy_links" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bb6a70be63d2ea0bede255cc3" ON "genealogy_links" ("organization_id", "material_lot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faeec9e2f42fd619af7e19b962" ON "genealogy_links" ("organization_id", "serial_id") `);
        await queryRunner.query(`CREATE TYPE "public"."form_templates_type_enum" AS ENUM('ncr', 'inspection', 'checklist', 'capa', 'other')`);
        await queryRunner.query(`CREATE TABLE "form_templates" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" "public"."form_templates_type_enum" NOT NULL DEFAULT 'other', "schema" jsonb, "version" integer NOT NULL DEFAULT '1', "library_origin_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dda93f70be71cb4a2e496b5ae49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0d79f225ba8c4a0ebf69d9e98" ON "form_templates" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c7c45b39c56400d9c81cc1204" ON "form_templates" ("library_origin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_873e21455abfe1c962e49ea272" ON "form_templates" ("organization_id", "type") `);
        await queryRunner.query(`CREATE TABLE "support_tickets" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying(30) NOT NULL, "subject" character varying(200) NOT NULL, "description" text NOT NULL, "category" character varying(30) NOT NULL DEFAULT 'other', "priority" character varying(20) NOT NULL DEFAULT 'normal', "status" character varying(20) NOT NULL DEFAULT 'open', "raised_by_user_id" uuid, "raised_by_name" character varying(200), "raised_by_email" character varying(255), "assigned_to_user_id" uuid, "assigned_to_name" character varying(200), "context_url" character varying(500), "app_version" character varying(50), "last_message_at" TIMESTAMP, "first_response_at" TIMESTAMP, "resolved_at" TIMESTAMP, "closed_at" TIMESTAMP, "version" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d260da44741e5cb4df0d628ea4" ON "support_tickets" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4dbd7a948ea8901cf5742dafc0" ON "support_tickets" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_04574eaf14f1ffa833597a1e0c" ON "support_tickets" ("assigned_to_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc72a9fd0d98be2e147ebbffa4" ON "support_tickets" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TABLE "support_ticket_messages" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "author_user_id" uuid, "author_name" character varying(200), "author_kind" character varying(20) NOT NULL DEFAULT 'customer', "body" text NOT NULL, "internal" boolean NOT NULL DEFAULT false, "attachments" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c3e561853b6b303f74fde5a3e1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c7e8e1938f8f4508e0d09e247" ON "support_ticket_messages" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4339162c880269e72a10a4e08a" ON "support_ticket_messages" ("ticket_id") `);
        await queryRunner.query(`CREATE TYPE "public"."materials_type_enum" AS ENUM('sheet', 'plate', 'bar', 'tube', 'coil', 'fastener', 'consumable', 'component', 'other')`);
        await queryRunner.query(`CREATE TABLE "materials" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."materials_type_enum" NOT NULL DEFAULT 'other', "unit_of_measure" character varying(20) NOT NULL DEFAULT 'ea', "specification" text, "profile" character varying(120), "material_grade" character varying(60), "unit_cost" numeric(12,2) NOT NULL DEFAULT '0', "reorder_level" numeric(14,3) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2fd1a93ecb222a28bef28663fa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ded767be5cae9863fbe23ba92" ON "materials" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c93c2c6d9656551b588c422f5f" ON "materials" ("organization_id", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('receipt', 'issue', 'scrap', 'adjustment', 'reserve', 'release', 'return')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "material_id" uuid NOT NULL, "type" "public"."stock_movements_type_enum" NOT NULL, "quantity" numeric(14,3) NOT NULL, "unit_cost" numeric(12,2), "location" character varying(100) NOT NULL DEFAULT 'MAIN', "work_order_id" uuid, "production_order_id" uuid, "reference" character varying(255), "note" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0203a72d5b60f5caebd91906f6" ON "stock_movements" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a917335f91daf5a470bfc283d" ON "stock_movements" ("organization_id", "work_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e69bfd016f0c0604afb38de5d3" ON "stock_movements" ("organization_id", "production_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_40cd22dbe259dbce7bce7dda7f" ON "stock_movements" ("organization_id", "material_id") `);
        await queryRunner.query(`CREATE TABLE "material_stock" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "material_id" uuid NOT NULL, "location" character varying(100) NOT NULL DEFAULT 'MAIN', "quantity_on_hand" numeric(14,3) NOT NULL DEFAULT '0', "quantity_reserved" numeric(14,3) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_892c48f1910e7a792726267bd6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db8ae98901406e3723a2602678" ON "material_stock" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d3f41eb2681d4c62c15a37a499" ON "material_stock" ("organization_id", "material_id", "location") `);
        await queryRunner.query(`CREATE TYPE "public"."equipment_type_enum" AS ENUM('laser', 'press_brake', 'cnc', 'welder', 'shear', 'grinder', 'paint_booth', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."equipment_status_enum" AS ENUM('running', 'idle', 'down', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "equipment" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."equipment_type_enum" NOT NULL DEFAULT 'other', "line_id" uuid, "station_id" uuid, "status" "public"."equipment_status_enum" NOT NULL DEFAULT 'idle', "hourly_rate" numeric(12,2), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0722e1b9d6eb19f5874c1678740" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76586eeb8bfe20475dbc32c7c4" ON "equipment" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_51c8b18ca63df6b7fec4f416cc" ON "equipment" ("organization_id", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_orders_status_enum" AS ENUM('open', 'in_progress', 'done', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "maintenance_orders" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "equipment_id" uuid NOT NULL, "plan_id" uuid, "status" "public"."maintenance_orders_status_enum" NOT NULL DEFAULT 'open', "scheduled_for" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "assigned_user_id" uuid, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b3d32d75cce242299ca18ca0c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b09f8fb9a8459ef1cdca886d6a" ON "maintenance_orders" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_756a6e6a9b481b109daf1686ed" ON "maintenance_orders" ("organization_id", "equipment_id") `);
        await queryRunner.query(`CREATE TABLE "maintenance_plans" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "equipment_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "interval_days" integer NOT NULL DEFAULT '30', "last_done_at" TIMESTAMP, "next_due_at" TIMESTAMP, "instructions" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc2a330993cedb65505a154ac5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb43508a4c342aaf629140da70" ON "maintenance_plans" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_05d8c8927d44ea6328323cccd7" ON "maintenance_plans" ("organization_id", "equipment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."downtime_events_reason_enum" AS ENUM('breakdown', 'changeover', 'no_material', 'no_operator', 'planned_maintenance', 'quality', 'other')`);
        await queryRunner.query(`CREATE TABLE "downtime_events" ("organization_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "equipment_id" uuid NOT NULL, "reason" "public"."downtime_events_reason_enum" NOT NULL DEFAULT 'other', "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP, "duration_seconds" numeric(12,0), "note" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57acaa85a5b8d93e5a52f82de64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ab3f26bbbb64d2ca212817f5c" ON "downtime_events" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc762a8c43350ea288f1b1cfab" ON "downtime_events" ("organization_id", "equipment_id") `);
        await queryRunner.query(`ALTER TABLE "stages" ADD CONSTRAINT "FK_3eb9327120b27e6b63ff553da8f" FOREIGN KEY ("process_id") REFERENCES "processes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stations" ADD CONSTRAINT "FK_eaea2f17c886ab96e5f6616d951" FOREIGN KEY ("line_id") REFERENCES "lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_files" ADD CONSTRAINT "FK_3e25f6cc8839b3c5cf03c11cc80" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" ADD CONSTRAINT "FK_a910eb33347fe03600a3728e955" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" ADD CONSTRAINT "FK_b32d209793a38a3ce2f239b9c59" FOREIGN KEY ("parent_id") REFERENCES "assembly_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" ADD CONSTRAINT "FK_b1d92504eb185b52b225803cec7" FOREIGN KEY ("import_file_id") REFERENCES "import_files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" ADD CONSTRAINT "FK_84f0a55cc93e152431a41f1f9db" FOREIGN KEY ("model_id") REFERENCES "models"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_632d5bf67f2803baf90906a4663" FOREIGN KEY ("process_id") REFERENCES "processes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_cf263781f73b223c293a5ac3e52" FOREIGN KEY ("line_id") REFERENCES "lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_45ee3a286c7e2713a27656df4d9" FOREIGN KEY ("assembly_node_id") REFERENCES "assembly_nodes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_85dec2b2a3a8115c6585ee20c5c" FOREIGN KEY ("depends_on_id") REFERENCES "work_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission_grants" ADD CONSTRAINT "FK_2e9395b394d1491a03a9085ae7e" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" ADD CONSTRAINT "FK_9d98cc405fb37415b0bbc992965" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" ADD CONSTRAINT "FK_3779e6ef4e5b4abd4181c8881fc" FOREIGN KEY ("stage_id") REFERENCES "stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" ADD CONSTRAINT "FK_c4ed7fce1defba762c07501e574" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" ADD CONSTRAINT "FK_20688314107afabe5d20a1c7936" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_7ec7d2aa1dfda0adce80db9eb2f" FOREIGN KEY ("work_order_stage_id") REFERENCES "work_order_stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_8b64bb9967011be0dc73d090280" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_orders" ADD CONSTRAINT "FK_158c0af45ca84f76e5ea531dc2b" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_items" ADD CONSTRAINT "FK_ccc68015ca35631ff542230b209" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_items" ADD CONSTRAINT "FK_6ac804d6add88cce9fc68f2a5fc" FOREIGN KEY ("assembly_node_id") REFERENCES "assembly_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_5f4b4f6491700ecacd29d031462" FOREIGN KEY ("production_order_id") REFERENCES "production_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_51c8fb04ceaf9a2533686e75578" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_data" ADD CONSTRAINT "FK_2ed8b637832186f1a0a092a158a" FOREIGN KEY ("model_id") REFERENCES "models"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "piece_lot_assignments" ADD CONSTRAINT "FK_a5ec726f130adf0603bf999d900" FOREIGN KEY ("node_id") REFERENCES "assembly_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "piece_lot_assignments" ADD CONSTRAINT "FK_3f553480ff8c5f7e0f1b331ea1d" FOREIGN KEY ("material_lot_id") REFERENCES "material_lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assembly_documents" ADD CONSTRAINT "FK_901daaec4dbceb0444c75518943" FOREIGN KEY ("node_id") REFERENCES "assembly_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_file_events" ADD CONSTRAINT "FK_627c8bd2a3aa9d45af9b3b08587" FOREIGN KEY ("import_file_id") REFERENCES "import_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drawings" ADD CONSTRAINT "FK_77a503e1f6744beaa7e2586fafd" FOREIGN KEY ("model_id") REFERENCES "models"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coordination_packages" ADD CONSTRAINT "FK_78c024fd398efb688f4618042c1" FOREIGN KEY ("model_id") REFERENCES "models"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_fe59c463f888b8ee0da19404b14" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_skills" ADD CONSTRAINT "FK_d27f44563392b7a95805bcc5f0e" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_ticket_messages" ADD CONSTRAINT "FK_4339162c880269e72a10a4e08ad" FOREIGN KEY ("ticket_id") REFERENCES "support_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_8bf5e361bdce822486fee95e6ea" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_stock" ADD CONSTRAINT "FK_2ec8f72a7c6215b7545ca419bc0" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_orders" ADD CONSTRAINT "FK_28a75382afcecada245c20ca437" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_plans" ADD CONSTRAINT "FK_38f013990c92480e7b45b520054" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "downtime_events" ADD CONSTRAINT "FK_d593d1aa214965055cdea737559" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "downtime_events" DROP CONSTRAINT "FK_d593d1aa214965055cdea737559"`);
        await queryRunner.query(`ALTER TABLE "maintenance_plans" DROP CONSTRAINT "FK_38f013990c92480e7b45b520054"`);
        await queryRunner.query(`ALTER TABLE "maintenance_orders" DROP CONSTRAINT "FK_28a75382afcecada245c20ca437"`);
        await queryRunner.query(`ALTER TABLE "material_stock" DROP CONSTRAINT "FK_2ec8f72a7c6215b7545ca419bc0"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_8bf5e361bdce822486fee95e6ea"`);
        await queryRunner.query(`ALTER TABLE "support_ticket_messages" DROP CONSTRAINT "FK_4339162c880269e72a10a4e08ad"`);
        await queryRunner.query(`ALTER TABLE "employee_skills" DROP CONSTRAINT "FK_d27f44563392b7a95805bcc5f0e"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_fe59c463f888b8ee0da19404b14"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "coordination_packages" DROP CONSTRAINT "FK_78c024fd398efb688f4618042c1"`);
        await queryRunner.query(`ALTER TABLE "drawings" DROP CONSTRAINT "FK_77a503e1f6744beaa7e2586fafd"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "import_file_events" DROP CONSTRAINT "FK_627c8bd2a3aa9d45af9b3b08587"`);
        await queryRunner.query(`ALTER TABLE "assembly_documents" DROP CONSTRAINT "FK_901daaec4dbceb0444c75518943"`);
        await queryRunner.query(`ALTER TABLE "piece_lot_assignments" DROP CONSTRAINT "FK_3f553480ff8c5f7e0f1b331ea1d"`);
        await queryRunner.query(`ALTER TABLE "piece_lot_assignments" DROP CONSTRAINT "FK_a5ec726f130adf0603bf999d900"`);
        await queryRunner.query(`ALTER TABLE "quality_data" DROP CONSTRAINT "FK_2ed8b637832186f1a0a092a158a"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_51c8fb04ceaf9a2533686e75578"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_5f4b4f6491700ecacd29d031462"`);
        await queryRunner.query(`ALTER TABLE "shipment_items" DROP CONSTRAINT "FK_6ac804d6add88cce9fc68f2a5fc"`);
        await queryRunner.query(`ALTER TABLE "shipment_items" DROP CONSTRAINT "FK_ccc68015ca35631ff542230b209"`);
        await queryRunner.query(`ALTER TABLE "production_orders" DROP CONSTRAINT "FK_158c0af45ca84f76e5ea531dc2b"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_8b64bb9967011be0dc73d090280"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_7ec7d2aa1dfda0adce80db9eb2f"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" DROP CONSTRAINT "FK_20688314107afabe5d20a1c7936"`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" DROP CONSTRAINT "FK_c4ed7fce1defba762c07501e574"`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" DROP CONSTRAINT "FK_3779e6ef4e5b4abd4181c8881fc"`);
        await queryRunner.query(`ALTER TABLE "work_order_stages" DROP CONSTRAINT "FK_9d98cc405fb37415b0bbc992965"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "role_permission_grants" DROP CONSTRAINT "FK_2e9395b394d1491a03a9085ae7e"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_85dec2b2a3a8115c6585ee20c5c"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_45ee3a286c7e2713a27656df4d9"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_cf263781f73b223c293a5ac3e52"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_632d5bf67f2803baf90906a4663"`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" DROP CONSTRAINT "FK_84f0a55cc93e152431a41f1f9db"`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" DROP CONSTRAINT "FK_b1d92504eb185b52b225803cec7"`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" DROP CONSTRAINT "FK_b32d209793a38a3ce2f239b9c59"`);
        await queryRunner.query(`ALTER TABLE "assembly_nodes" DROP CONSTRAINT "FK_a910eb33347fe03600a3728e955"`);
        await queryRunner.query(`ALTER TABLE "import_files" DROP CONSTRAINT "FK_3e25f6cc8839b3c5cf03c11cc80"`);
        await queryRunner.query(`ALTER TABLE "stations" DROP CONSTRAINT "FK_eaea2f17c886ab96e5f6616d951"`);
        await queryRunner.query(`ALTER TABLE "stages" DROP CONSTRAINT "FK_3eb9327120b27e6b63ff553da8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc762a8c43350ea288f1b1cfab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ab3f26bbbb64d2ca212817f5c"`);
        await queryRunner.query(`DROP TABLE "downtime_events"`);
        await queryRunner.query(`DROP TYPE "public"."downtime_events_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05d8c8927d44ea6328323cccd7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb43508a4c342aaf629140da70"`);
        await queryRunner.query(`DROP TABLE "maintenance_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_756a6e6a9b481b109daf1686ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b09f8fb9a8459ef1cdca886d6a"`);
        await queryRunner.query(`DROP TABLE "maintenance_orders"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51c8b18ca63df6b7fec4f416cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76586eeb8bfe20475dbc32c7c4"`);
        await queryRunner.query(`DROP TABLE "equipment"`);
        await queryRunner.query(`DROP TYPE "public"."equipment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."equipment_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3f41eb2681d4c62c15a37a499"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db8ae98901406e3723a2602678"`);
        await queryRunner.query(`DROP TABLE "material_stock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40cd22dbe259dbce7bce7dda7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e69bfd016f0c0604afb38de5d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a917335f91daf5a470bfc283d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0203a72d5b60f5caebd91906f6"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c93c2c6d9656551b588c422f5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ded767be5cae9863fbe23ba92"`);
        await queryRunner.query(`DROP TABLE "materials"`);
        await queryRunner.query(`DROP TYPE "public"."materials_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4339162c880269e72a10a4e08a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c7e8e1938f8f4508e0d09e247"`);
        await queryRunner.query(`DROP TABLE "support_ticket_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc72a9fd0d98be2e147ebbffa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04574eaf14f1ffa833597a1e0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4dbd7a948ea8901cf5742dafc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d260da44741e5cb4df0d628ea4"`);
        await queryRunner.query(`DROP TABLE "support_tickets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_873e21455abfe1c962e49ea272"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c7c45b39c56400d9c81cc1204"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0d79f225ba8c4a0ebf69d9e98"`);
        await queryRunner.query(`DROP TABLE "form_templates"`);
        await queryRunner.query(`DROP TYPE "public"."form_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faeec9e2f42fd619af7e19b962"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bb6a70be63d2ea0bede255cc3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6aea3bacc6a4c6a40cbf63a35"`);
        await queryRunner.query(`DROP TABLE "genealogy_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d8cd27d8289ad569661e0786e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79657a3cb8c19f6301ea7d6b73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b72b223a1faab13611a89c3bad"`);
        await queryRunner.query(`DROP TABLE "serial_units"`);
        await queryRunner.query(`DROP TYPE "public"."serial_units_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e04118de3e868864d6a56a0cda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14db12e7c45733ec3a07d1160c"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ec563056f0d5955ed01edc340"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54858677e7532654a5fc12b994"`);
        await queryRunner.query(`DROP TABLE "employee_skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39939165471c9a9d17325edc87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a4882243be4521b3aad46e74e"`);
        await queryRunner.query(`DROP TABLE "shift_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ff650d103d30e94e1e9ea2163"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_617f093918468c351bf240eea4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d51714a98b706cc16e11f8f3f"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c519fa5a72f430878c903cde75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61b3cb192f70b46dcaf7ca293f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a31251121c74bea553cffa061"`);
        await queryRunner.query(`DROP TABLE "conversion_jobs"`);
        await queryRunner.query(`DROP TABLE "coordination_packages"`);
        await queryRunner.query(`DROP TABLE "drawings"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_491e12de5d7a90a5423fc8072c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_627c8bd2a3aa9d45af9b3b0858"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f2bede4beb15c252a3dcacac6"`);
        await queryRunner.query(`DROP TABLE "import_file_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ada568171c79bbb5571b2a2a59"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_901daaec4dbceb0444c7551894"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ef39c4083166064de6685d38c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99d3e233142b752977c13bfab9"`);
        await queryRunner.query(`DROP TABLE "assembly_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ce72a36dc648bf61e13b10ab6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5ec726f130adf0603bf999d90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f553480ff8c5f7e0f1b331ea1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d48c311c2c30f55009bff846bf"`);
        await queryRunner.query(`DROP TABLE "piece_lot_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55ba706b1d82e2d6fb7df3ce4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1375b8eb706d8125fd8fe78fc9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_668889d42df3e9a9af7577f331"`);
        await queryRunner.query(`DROP TABLE "material_lots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2bfde750b655d3650bf644a73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bea2a0f82f98179feec4a26961"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c91381ec2180cee025ad8e243a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cab557211fa4769d2c1de5df37"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_quality_data_org_client_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4710e9b0f5968609f1109d42b0"`);
        await queryRunner.query(`DROP TABLE "quality_data"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_970334f619ba2b1ce2a2dfbb29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71e829797490fa916e92a5603f"`);
        await queryRunner.query(`DROP TABLE "quality_report_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5357c80fe58ddf03ba26244de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76f65e714e475e6c0463db1b45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a30142ee6935923ecfa7215c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76f8c9297ae2598ae43b169a14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a2789da6c45f6d263954b0964"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_361c1a31a625fb13f609b06897"`);
        await queryRunner.query(`DROP TABLE "quality_reports"`);
        await queryRunner.query(`DROP TYPE "public"."quality_reports_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a00e535c74076ab850ff565b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91cdde92701b89379e45888412"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a2ee35581721926841ca73b31"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_793441b3ca5b4e860cbbc0ba63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40f37aa9652926851c630281e5"`);
        await queryRunner.query(`DROP TABLE "shipment_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc9d16f42c918512af1d0ac33b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d48deb499cd3c305e5ee88794f"`);
        await queryRunner.query(`DROP TABLE "production_orders"`);
        await queryRunner.query(`DROP TYPE "public"."production_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1ad7e6b1c1fb01c90b557effb"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_input_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53da8dfea1358f1dd838ed483d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b253ddb0efc29fd573fd353e88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70a8a30750743c1f083ab452b3"`);
        await queryRunner.query(`DROP TABLE "work_order_stage_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2abb3c5f7c23f6ea78cc9f0391"`);
        await queryRunner.query(`DROP TABLE "work_order_stages"`);
        await queryRunner.query(`DROP TYPE "public"."work_order_stages_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21a659804ed7bf61eb91688dea"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_system_name"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_org_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c328a1ecd12a5f153a96df4509"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."uq_role_permission_grant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e9395b394d1491a03a9085ae7"`);
        await queryRunner.query(`DROP TABLE "role_permission_grants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce134ea8fbde02d6ea7ef47689"`);
        await queryRunner.query(`DROP TABLE "work_orders"`);
        await queryRunner.query(`DROP TYPE "public"."work_orders_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f18710a23bb84e19152c03702"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_381643ecf1cbccbdd4cf2202ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_487a5538402a7d98120d2f67ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66019f5d0f82c8f82e0086a8bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f7afa487ac07d715765f29dcf"`);
        await queryRunner.query(`DROP TABLE "assembly_nodes"`);
        await queryRunner.query(`DROP TYPE "public"."assembly_nodes_node_type_enum"`);
        await queryRunner.query(`DROP TABLE "models"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2660bc3e8efca00003ad93568f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_585c8ce06628c70b70100bfb84"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35f1f7d05b762cd089a73eaff8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b4bbc007af39ae1898af1e6b9"`);
        await queryRunner.query(`DROP TABLE "import_files"`);
        await queryRunner.query(`DROP TYPE "public"."import_files_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_lines_org_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fcadab7665a53629719a6c7de"`);
        await queryRunner.query(`DROP TABLE "lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fecc585b9225ade4dc2b28e47"`);
        await queryRunner.query(`DROP TABLE "stations"`);
        await queryRunner.query(`DROP TYPE "public"."stations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c520fd9491180bab8038d68ed9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76392b0d423d52a89de847905c"`);
        await queryRunner.query(`DROP TABLE "processes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_788b52632a8883adcab17800b9"`);
        await queryRunner.query(`DROP TABLE "stages"`);
    }

}
